//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HesabDari.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Accounting
    {
        public int id { get; set; }
        public int PersonId { get; set; }
        public int TypeId { get; set; }
        public double Amount { get; set; }
        public System.DateTime Date { get; set; }
        public string Description { get; set; }
    
        public virtual AccountingType AccountingType { get; set; }
        public virtual Persons Persons { get; set; }
    }
}
